// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.12.4
// source: proto/v1/go_shortener.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortURLResponse_Status int32

const (
	CreateShortURLResponse_CREATED        CreateShortURLResponse_Status = 0
	CreateShortURLResponse_ALREADY_EXISTS CreateShortURLResponse_Status = 1
)

// Enum value maps for CreateShortURLResponse_Status.
var (
	CreateShortURLResponse_Status_name = map[int32]string{
		0: "CREATED",
		1: "ALREADY_EXISTS",
	}
	CreateShortURLResponse_Status_value = map[string]int32{
		"CREATED":        0,
		"ALREADY_EXISTS": 1,
	}
)

func (x CreateShortURLResponse_Status) Enum() *CreateShortURLResponse_Status {
	p := new(CreateShortURLResponse_Status)
	*p = x
	return p
}

func (x CreateShortURLResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateShortURLResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_go_shortener_proto_enumTypes[0].Descriptor()
}

func (CreateShortURLResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_v1_go_shortener_proto_enumTypes[0]
}

func (x CreateShortURLResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateShortURLResponse_Status.Descriptor instead.
func (CreateShortURLResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{1, 0}
}

type GetFullByIDResponse_Status int32

const (
	GetFullByIDResponse_OK        GetFullByIDResponse_Status = 0
	GetFullByIDResponse_DELETED   GetFullByIDResponse_Status = 1
	GetFullByIDResponse_NOT_FOUND GetFullByIDResponse_Status = 2
)

// Enum value maps for GetFullByIDResponse_Status.
var (
	GetFullByIDResponse_Status_name = map[int32]string{
		0: "OK",
		1: "DELETED",
		2: "NOT_FOUND",
	}
	GetFullByIDResponse_Status_value = map[string]int32{
		"OK":        0,
		"DELETED":   1,
		"NOT_FOUND": 2,
	}
)

func (x GetFullByIDResponse_Status) Enum() *GetFullByIDResponse_Status {
	p := new(GetFullByIDResponse_Status)
	*p = x
	return p
}

func (x GetFullByIDResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetFullByIDResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_go_shortener_proto_enumTypes[1].Descriptor()
}

func (GetFullByIDResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_v1_go_shortener_proto_enumTypes[1]
}

func (x GetFullByIDResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetFullByIDResponse_Status.Descriptor instead.
func (GetFullByIDResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{9, 0}
}

type CreateShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // original url to shorten
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLRequest) Reset() {
	*x = CreateShortURLRequest{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLRequest) ProtoMessage() {}

func (x *CreateShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLRequest.ProtoReflect.Descriptor instead.
func (*CreateShortURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateShortURLResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	NewJwtToken   string                        `protobuf:"bytes,1,opt,name=new_jwt_token,json=newJwtToken,proto3" json:"new_jwt_token,omitempty"` // new token after first call of user or after refreshing
	Result        string                        `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                                // resulting short url
	Status        CreateShortURLResponse_Status `protobuf:"varint,3,opt,name=status,proto3,enum=go_shortener.v1.CreateShortURLResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLResponse) Reset() {
	*x = CreateShortURLResponse{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLResponse) ProtoMessage() {}

func (x *CreateShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLResponse.ProtoReflect.Descriptor instead.
func (*CreateShortURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortURLResponse) GetNewJwtToken() string {
	if x != nil {
		return x.NewJwtToken
	}
	return ""
}

func (x *CreateShortURLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CreateShortURLResponse) GetStatus() CreateShortURLResponse_Status {
	if x != nil {
		return x.Status
	}
	return CreateShortURLResponse_CREATED
}

type BatchCreateShortURLRequestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` // original url to shorten
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateShortURLRequestItem) Reset() {
	*x = BatchCreateShortURLRequestItem{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateShortURLRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateShortURLRequestItem) ProtoMessage() {}

func (x *BatchCreateShortURLRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateShortURLRequestItem.ProtoReflect.Descriptor instead.
func (*BatchCreateShortURLRequestItem) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *BatchCreateShortURLRequestItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchCreateShortURLRequestItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type BatchCreateShortURLResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"` // resulting short url
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateShortURLResponseItem) Reset() {
	*x = BatchCreateShortURLResponseItem{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateShortURLResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateShortURLResponseItem) ProtoMessage() {}

func (x *BatchCreateShortURLResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateShortURLResponseItem.ProtoReflect.Descriptor instead.
func (*BatchCreateShortURLResponseItem) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *BatchCreateShortURLResponseItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchCreateShortURLResponseItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type BatchCreateShortURLRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Urls          []*BatchCreateShortURLRequestItem `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateShortURLRequest) Reset() {
	*x = BatchCreateShortURLRequest{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateShortURLRequest) ProtoMessage() {}

func (x *BatchCreateShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateShortURLRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateShortURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCreateShortURLRequest) GetUrls() []*BatchCreateShortURLRequestItem {
	if x != nil {
		return x.Urls
	}
	return nil
}

type BatchCreateShortURLResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	NewJwtToken   string                             `protobuf:"bytes,1,opt,name=new_jwt_token,json=newJwtToken,proto3" json:"new_jwt_token,omitempty"` // new token after first call of user or after refreshing
	Results       []*BatchCreateShortURLResponseItem `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateShortURLResponse) Reset() {
	*x = BatchCreateShortURLResponse{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateShortURLResponse) ProtoMessage() {}

func (x *BatchCreateShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateShortURLResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateShortURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *BatchCreateShortURLResponse) GetNewJwtToken() string {
	if x != nil {
		return x.NewJwtToken
	}
	return ""
}

func (x *BatchCreateShortURLResponse) GetResults() []*BatchCreateShortURLResponseItem {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteShortURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortURLsRequest) Reset() {
	*x = DeleteShortURLsRequest{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortURLsRequest) ProtoMessage() {}

func (x *DeleteShortURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteShortURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteShortURLsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteShortURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewJwtToken   string                 `protobuf:"bytes,1,opt,name=new_jwt_token,json=newJwtToken,proto3" json:"new_jwt_token,omitempty"` // new token after first call of user or after refreshing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortURLsResponse) Reset() {
	*x = DeleteShortURLsResponse{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortURLsResponse) ProtoMessage() {}

func (x *DeleteShortURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteShortURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteShortURLsResponse) GetNewJwtToken() string {
	if x != nil {
		return x.NewJwtToken
	}
	return ""
}

type GetFullByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // short url id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullByIDRequest) Reset() {
	*x = GetFullByIDRequest{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullByIDRequest) ProtoMessage() {}

func (x *GetFullByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullByIDRequest.ProtoReflect.Descriptor instead.
func (*GetFullByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *GetFullByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFullByIDResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	FullUrl       string                     `protobuf:"bytes,1,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"` // original url
	Status        GetFullByIDResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=go_shortener.v1.GetFullByIDResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullByIDResponse) Reset() {
	*x = GetFullByIDResponse{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullByIDResponse) ProtoMessage() {}

func (x *GetFullByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullByIDResponse.ProtoReflect.Descriptor instead.
func (*GetFullByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *GetFullByIDResponse) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *GetFullByIDResponse) GetStatus() GetFullByIDResponse_Status {
	if x != nil {
		return x.Status
	}
	return GetFullByIDResponse_OK
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealIp        string                 `protobuf:"bytes,1,opt,name=real_ip,json=realIp,proto3" json:"real_ip,omitempty"` // to check trusted subnet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatsRequest) GetRealIp() string {
	if x != nil {
		return x.RealIp
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          uint32                 `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`   // total urls shortened
	Users         uint32                 `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"` // total users
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatsResponse) GetUrls() uint32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetStatsResponse) GetUsers() uint32 {
	if x != nil {
		return x.Users
	}
	return 0
}

type GetUserShortURLsResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserShortURLsResponseItem) Reset() {
	*x = GetUserShortURLsResponseItem{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserShortURLsResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserShortURLsResponseItem) ProtoMessage() {}

func (x *GetUserShortURLsResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserShortURLsResponseItem.ProtoReflect.Descriptor instead.
func (*GetUserShortURLsResponseItem) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserShortURLsResponseItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *GetUserShortURLsResponseItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetUserShortURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserShortURLsRequest) Reset() {
	*x = GetUserShortURLsRequest{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserShortURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserShortURLsRequest) ProtoMessage() {}

func (x *GetUserShortURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserShortURLsRequest.ProtoReflect.Descriptor instead.
func (*GetUserShortURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{13}
}

type GetUserShortURLsResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	NewJwtToken   string                          `protobuf:"bytes,1,opt,name=new_jwt_token,json=newJwtToken,proto3" json:"new_jwt_token,omitempty"` // new token after first call of user or after refreshing
	Urls          []*GetUserShortURLsResponseItem `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserShortURLsResponse) Reset() {
	*x = GetUserShortURLsResponse{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserShortURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserShortURLsResponse) ProtoMessage() {}

func (x *GetUserShortURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserShortURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserShortURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserShortURLsResponse) GetNewJwtToken() string {
	if x != nil {
		return x.NewJwtToken
	}
	return ""
}

func (x *GetUserShortURLsResponse) GetUrls() []*GetUserShortURLsResponseItem {
	if x != nil {
		return x.Urls
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{15}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_v1_go_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_go_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_go_shortener_proto_rawDescGZIP(), []int{16}
}

var File_proto_v1_go_shortener_proto protoreflect.FileDescriptor

var file_proto_v1_go_shortener_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x5f, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67,
	0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x29,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0xc7, 0x01, 0x0a, 0x16, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x5f, 0x6a, 0x77, 0x74, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x77,
	0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x46, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2e, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x29, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54,
	0x53, 0x10, 0x01, 0x22, 0x6a, 0x0a, 0x1e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22,
	0x65, 0x0a, 0x1f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x61, 0x0a, 0x1a, 0x42, 0x61, 0x74, 0x63, 0x68, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x1b, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x65, 0x77,
	0x5f, 0x6a, 0x77, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6e, 0x65, 0x77, 0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x4a, 0x0a,
	0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x2a, 0x0a, 0x16, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x3d, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x5f, 0x6a, 0x77, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x4a, 0x77, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x72, 0x6c, 0x12, 0x43, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e,
	0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x2c, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x02,
	0x22, 0x2a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x69, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x6c, 0x49, 0x70, 0x22, 0x3c, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x5e, 0x0a, 0x1c, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x5f, 0x6a, 0x77, 0x74, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x4a, 0x77,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x41, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa8, 0x05, 0x0a, 0x12, 0x47, 0x6f, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x61, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x12, 0x26, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55,
	0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x6f, 0x5f, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x70, 0x0a, 0x13, 0x42, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x2b, 0x2e, 0x67, 0x6f, 0x5f, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x27, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x46, 0x75, 0x6c, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x12, 0x23, 0x2e, 0x67, 0x6f, 0x5f, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x75, 0x6c, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x20, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x28, 0x2e, 0x67, 0x6f, 0x5f, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x44, 0x79, 0x61, 0x64, 0x79, 0x61, 0x52, 0x6f, 0x64, 0x79, 0x61, 0x2f, 0x67, 0x6f,
	0x2d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_go_shortener_proto_rawDescOnce sync.Once
	file_proto_v1_go_shortener_proto_rawDescData = file_proto_v1_go_shortener_proto_rawDesc
)

func file_proto_v1_go_shortener_proto_rawDescGZIP() []byte {
	file_proto_v1_go_shortener_proto_rawDescOnce.Do(func() {
		file_proto_v1_go_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_go_shortener_proto_rawDescData)
	})
	return file_proto_v1_go_shortener_proto_rawDescData
}

var file_proto_v1_go_shortener_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_v1_go_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_v1_go_shortener_proto_goTypes = []any{
	(CreateShortURLResponse_Status)(0),      // 0: go_shortener.v1.CreateShortURLResponse.Status
	(GetFullByIDResponse_Status)(0),         // 1: go_shortener.v1.GetFullByIDResponse.Status
	(*CreateShortURLRequest)(nil),           // 2: go_shortener.v1.CreateShortURLRequest
	(*CreateShortURLResponse)(nil),          // 3: go_shortener.v1.CreateShortURLResponse
	(*BatchCreateShortURLRequestItem)(nil),  // 4: go_shortener.v1.BatchCreateShortURLRequestItem
	(*BatchCreateShortURLResponseItem)(nil), // 5: go_shortener.v1.BatchCreateShortURLResponseItem
	(*BatchCreateShortURLRequest)(nil),      // 6: go_shortener.v1.BatchCreateShortURLRequest
	(*BatchCreateShortURLResponse)(nil),     // 7: go_shortener.v1.BatchCreateShortURLResponse
	(*DeleteShortURLsRequest)(nil),          // 8: go_shortener.v1.DeleteShortURLsRequest
	(*DeleteShortURLsResponse)(nil),         // 9: go_shortener.v1.DeleteShortURLsResponse
	(*GetFullByIDRequest)(nil),              // 10: go_shortener.v1.GetFullByIDRequest
	(*GetFullByIDResponse)(nil),             // 11: go_shortener.v1.GetFullByIDResponse
	(*GetStatsRequest)(nil),                 // 12: go_shortener.v1.GetStatsRequest
	(*GetStatsResponse)(nil),                // 13: go_shortener.v1.GetStatsResponse
	(*GetUserShortURLsResponseItem)(nil),    // 14: go_shortener.v1.GetUserShortURLsResponseItem
	(*GetUserShortURLsRequest)(nil),         // 15: go_shortener.v1.GetUserShortURLsRequest
	(*GetUserShortURLsResponse)(nil),        // 16: go_shortener.v1.GetUserShortURLsResponse
	(*PingRequest)(nil),                     // 17: go_shortener.v1.PingRequest
	(*PingResponse)(nil),                    // 18: go_shortener.v1.PingResponse
}
var file_proto_v1_go_shortener_proto_depIdxs = []int32{
	0,  // 0: go_shortener.v1.CreateShortURLResponse.status:type_name -> go_shortener.v1.CreateShortURLResponse.Status
	4,  // 1: go_shortener.v1.BatchCreateShortURLRequest.urls:type_name -> go_shortener.v1.BatchCreateShortURLRequestItem
	5,  // 2: go_shortener.v1.BatchCreateShortURLResponse.results:type_name -> go_shortener.v1.BatchCreateShortURLResponseItem
	1,  // 3: go_shortener.v1.GetFullByIDResponse.status:type_name -> go_shortener.v1.GetFullByIDResponse.Status
	14, // 4: go_shortener.v1.GetUserShortURLsResponse.urls:type_name -> go_shortener.v1.GetUserShortURLsResponseItem
	2,  // 5: go_shortener.v1.GoShortenerService.CreateShortURL:input_type -> go_shortener.v1.CreateShortURLRequest
	6,  // 6: go_shortener.v1.GoShortenerService.BatchCreateShortURL:input_type -> go_shortener.v1.BatchCreateShortURLRequest
	8,  // 7: go_shortener.v1.GoShortenerService.DeleteShortURLs:input_type -> go_shortener.v1.DeleteShortURLsRequest
	10, // 8: go_shortener.v1.GoShortenerService.GetFullByID:input_type -> go_shortener.v1.GetFullByIDRequest
	12, // 9: go_shortener.v1.GoShortenerService.GetStats:input_type -> go_shortener.v1.GetStatsRequest
	15, // 10: go_shortener.v1.GoShortenerService.GetUserShortURLs:input_type -> go_shortener.v1.GetUserShortURLsRequest
	17, // 11: go_shortener.v1.GoShortenerService.Ping:input_type -> go_shortener.v1.PingRequest
	3,  // 12: go_shortener.v1.GoShortenerService.CreateShortURL:output_type -> go_shortener.v1.CreateShortURLResponse
	7,  // 13: go_shortener.v1.GoShortenerService.BatchCreateShortURL:output_type -> go_shortener.v1.BatchCreateShortURLResponse
	9,  // 14: go_shortener.v1.GoShortenerService.DeleteShortURLs:output_type -> go_shortener.v1.DeleteShortURLsResponse
	11, // 15: go_shortener.v1.GoShortenerService.GetFullByID:output_type -> go_shortener.v1.GetFullByIDResponse
	13, // 16: go_shortener.v1.GoShortenerService.GetStats:output_type -> go_shortener.v1.GetStatsResponse
	16, // 17: go_shortener.v1.GoShortenerService.GetUserShortURLs:output_type -> go_shortener.v1.GetUserShortURLsResponse
	18, // 18: go_shortener.v1.GoShortenerService.Ping:output_type -> go_shortener.v1.PingResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_v1_go_shortener_proto_init() }
func file_proto_v1_go_shortener_proto_init() {
	if File_proto_v1_go_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_go_shortener_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_go_shortener_proto_goTypes,
		DependencyIndexes: file_proto_v1_go_shortener_proto_depIdxs,
		EnumInfos:         file_proto_v1_go_shortener_proto_enumTypes,
		MessageInfos:      file_proto_v1_go_shortener_proto_msgTypes,
	}.Build()
	File_proto_v1_go_shortener_proto = out.File
	file_proto_v1_go_shortener_proto_rawDesc = nil
	file_proto_v1_go_shortener_proto_goTypes = nil
	file_proto_v1_go_shortener_proto_depIdxs = nil
}
